### PR TITLE
Replace insert-css with insert-styles for browser detection

### PR DESCRIPTION
**Pull request by bendrucker**
No need to do this yourself

### CODE REVIEW

**Comment by bendrucker** [comment]
Also more importantly using `process` in your code ends up bringing in the process shim into browserify

**Comment by chinedufn** [comment]
@bendrucker thanks!

Looks like there's a merge conflict in this one. Made you a collaborator, feel free to merge this in :boom:

**Comment by bendrucker** [comment]
v1.0.2 ready for publish

**Comment by chinedufn** [comment]
Done, cheers!

**Pull request closed without merging**
